name: UI tests - Docker

on:
  #push:
  #  branches: [ main ] # Собираем при пуше в основную ветку
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #- name: Set up QEMU
      #  uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Load for tests
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          platforms: linux/amd64 
          tags: playwright-tests:local
          #tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          # Кэширование слоев для ускорения сборки
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Playwright tests in Docker
        run: |
          mkdir -p results
          docker run \
            -v ${{ github.workspace }}/results:/app/results:rw \
            --rm \
            playwright-tests:local \
            uv run pytest -m debug

      - name: Upload Allure Results # Сохраняем отчеты как артефакты GitHub
        if: always() # Запускать даже если тесты упали
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: results/allure-results
          retention-days: 1

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GHCR
        if: success() # Пушим только если тесты прошли (опционально)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true # Теперь отправляем в реестр
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha

  run-tests:
    if: false
    needs: build-and-push # Запускать только если сборка прошла успешно
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Playwright tests in Docker
        run: |
          mkdir -p results
          docker run \
            -v ${{ github.workspace }}/results:/app/results:rw \
            --rm \
            ghcr.io/${{ github.repository }}:latest \
            uv run pytest -m debug

      - name: Upload Allure Results # Сохраняем отчеты как артефакты GitHub
        if: always() # Запускать даже если тесты упали
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: results/allure-results
          retention-days: 1


  publish-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: always()
    needs: [ build-and-push ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Report
        uses: ./.github/actions/allure-rep

